apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: default
spec:
  encryptedData:
    # These are example encrypted values - you'll need to generate real ones using kubeseal
    # To create real sealed secrets, run:
    # echo -n 'your-secret-value' | kubectl create secret generic app-secrets --dry-run=client --from-file=db-password=/dev/stdin -o yaml | kubeseal -o yaml
    db-password: AgBy3i4OJSWK+PiTySYZZA9rO67phxzxvbSrvXbOMRy6n9WnBvRzjr+wT7gNk2+yKGfvN4uLVHJI8w4kT2C5hB7J3...
    api-key: AgDw4o/FCTQ9RpO8W3lHQwHnUCGH9+3x9W7T6+xwxBhPSmQ7VqYF4K8aNnD3oJfQx2pY5r6tE8gB1mNz9vP3L4...
  template:
    metadata:
      name: app-secrets
      namespace: default
    type: Opaque
